# KNN Algorithm in Supervised ML
## KNeighborsClassifier of sklearn library for this one

In [3]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [5]:
x = np.array([
    [1 ,3500],
    [2, 3200],
    [3, 3000],
    [4, 2500],
    [5, 2300],
    [6, 2000],
    [7, 2200],
    [2, 3700]
])

y = ['Unfit','Unfit','Unfit','Fit','Fit','Fit','Fit','Unfit']

In [7]:
#Create a model
model = KNeighborsClassifier(n_neighbors = 3)

In [9]:
#Train the model
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [12]:
#Predict
new_person = [[4.5, 2600]]
predict = model.predict(new_person)
print('Predicted Result: ', predict[0])

Predicted Result:  Fit

In [15]:
#Prediction from taking the values from users

exercise_hr = float(input('Enter number of exercise in hours: '))
cal_intake = float(input('Enter number of calories consume: '))
pred_fu = model.predict([[exercise_hr, cal_intake]])
print(f'Exercise Hours: {exercise_hr}, Calories Intake: {cal_intake}, So you are likely {pred_fu[0]}')

Enter number of exercise in hours:  2
Enter number of calories consume:  2333

Exercise Hours: 2.0, Calories Intake: 2333.0, So you are likely Fit

In [17]:
import pandas as pd

In [20]:
df_fruit = pd.read_csv('fruit_data.csv')
df_fruit

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange
4     180   7.5       ?

In [22]:
x = df_fruit[['Weight', 'Size']]
y = df_fruit['Fruit']

In [24]:
model_fruit = KNeighborsClassifier(n_neighbors = 3)
model_fruit.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [36]:
# new_fruit_data = [[150, 7.0]]
# new_fruit = pd.DataFrame(new_fruit_data, columns=['Weight', 'Size'])
fruit_weight = float(input('Enter the weight of fruit in gm: '))
fruit_size = float(input('Enter the size of fruit in cm: '))
new_fruit = pd.DataFrame([[fruit_weight, fruit_size]], columns=['Weight', 'Size'])
predict_fruit = model_fruit.predict(new_fruit)
print('The fruit is likel a/an ', predict_fruit[0])

Enter the weight of fruit in gm:  150
Enter the size of fruit in cm:  7

The fruit is likel a/an  Apple

In [41]:
fruit_weight = float(input('Enter the weight of fruit in gm: '))
fruit_size = float(input('Enter the size of fruit in cm: '))
predict_fruit = model_fruit.predict(pd.DataFrame([[fruit_weight, fruit_size]], columns=['Weight', 'Size']))
print('The fruit is likel a/an ', predict_fruit[0])

Enter the weight of fruit in gm:  180
Enter the size of fruit in cm:  7.5

The fruit is likel a/an  ?

## Predict a student's grade level (A,B,C)
- Based on hours studied and assigment completed
- usinh K-Nearest Neighbors Algorithm

In [74]:
df_stud_grade = pd.read_csv('student_grade.csv')
df_stud_grade

   Hours_Studied  Assignments_Completed Grade
0            1.5                      1     C
1            2.0                      2     C
2            3.0                      3     B
3            4.0                      4     B
4            5.0                      5     A
5            6.0                      6     A

In [75]:
x_stud = df_stud_grade[['Hours_Studied','Assignments_Completed']]
y_stud = df_stud_grade['Grade']

In [76]:
#Create Model
model_stud = KNeighborsClassifier(n_neighbors = 3)
model_stud.fit(x_stud,y_stud)

KNeighborsClassifier(n_neighbors=3)

In [80]:
#Predict
new_stud = [[1.5,1]]
pred_gred = model_stud.predict(pd.DataFrame(new_stud, columns=['Hours_Studied', 'Assignments_Completed']))
print('Grade', pred_gred[0])

Grade C