# Supervised learning

## Linear Regression

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
data = pd.read_csv('sales_data.csv')
data.head()

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000

In [3]:
x = data[['Advertising_Spend']]
y = data['Sales_Revenue']

In [4]:
model = LinearRegression()
model.fit(x,y)
# print('Training done')

LinearRegression()

In [5]:
new_spend = float(input('Enter New spend to predict sales revenue: '))
predicted_revenue = model.predict([[new_spend]])
print(f'Predicted sales revenue for RM{new_spend} ad spend: RM{predicted_revenue}')

Enter New spend to predict sales revenue:  2323

Predicted sales revenue for RM2323.0 ad spend: RM[19219.92857143]

D:\Anaconda\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## 1. Linear Regression - House price prediction 
- Goal: Train a Linear Regression model to predict house price from Size_sqft

In [22]:
df_house = pd.read_csv('house_price.csv')
df_house.head(6)

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000
5       1700       ?

In [14]:
df_house['Price'] = df_house['Price'].replace('?', np.nan)
df_house['Price'] = pd.to_numeric(df_house['Price'], errors='coerce')

In [15]:
df_house_cleaned = df_house.dropna(subset=['Size_sqft', 'Price'])

In [16]:
size_sqft = df_house_cleaned[['Size_sqft']]
price = df_house_cleaned['Price']

In [23]:
house_model = LinearRegression()
house_model.fit(size_sqft,price)
# print('Training done')

LinearRegression()

In [24]:
sqft_new = float(input('Enter sqft to predict house price: '))
predicted_price = house_model.predict([[sqft_new]])
print(f'Predicted house price for {sqft_new} is: RM{predicted_price}')

Enter sqft to predict house price:  2000

Predicted house price for 2000.0 is: RM[255676.47058824]

D:\Anaconda\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(